name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master
  
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: License Files
      uses: apache/skywalking-eyes@v0.4.0
      with:
        config: .github/.licenserc.yaml
        mode: fix
    - name: Commit any changes
        id: commit-changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'Committing clang-format changes'

    - uses: PaulRosenthal/Jekyll-Deploy-Test-Action@v3
      with:
        gemfile-location: '/docs'
        site-directory: '/docs'