name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master
  
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: License Files
      uses: apache/skywalking-eyes@v0.4.0
      with:
        config: .github/.licenserc.yaml
        mode: fix
    - uses: PaulRosenthal/Jekyll-Deploy-Test-Action@v3
      with:
        gemfile-location: '/docs'
        site-directory: '/docs'